logging:
    file:
        path: /data
    level:
        org:
            hibernate:
                type:
                    descriptor:
                        sql: debug
        root: info
        sql: debug
server:
    port: 8080
    servlet:
        context-path: /
spring:
    application:
        name: GreenUniv
        version: 0.0.1
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        hikari:
            connection-timeout: 10000
            maximum-pool-size: 20
        url: jdbc:mysql://13.209.7.78:3306/green_univ
        username: ec2-user
        password: p33wsu47r5b0
        #url: jdbc:mysql://greenuniv-db:3306/green_univ
        #username: ec2-user
        #password: p33wsu47r5b0
    devtools:
        livereload:
            enabled: true
    jpa:
        database: mysql
        hibernate:
            ddl-auto: none
            naming:
                physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        properties:
            hibernate:
                format_sql: true
                show_sql: true
    thymeleaf:
        prefix: classpath:/templates